stage('Verify Deployment') {
            steps {
                echo "====[ Stage 6: Verify Deployment ]====="
                sh '''
                    kubectl get deployments
                    kubectl get replicaset
                    kubectl get services
                    kubectl get pods
                    echo "✅ All resources deployed successfully"
                    echo "Service available on NodePort 30080"
                '''
            }
        }
